### PR TITLE
Contributor experience

### PR DESCRIPTION
**Pull request by samueldg**
⚠️ This PR contains a reformatting with [Black](https://github.com/psf/black), which is a Band Aid you rip once. I suggest reviewing commit by commit to better make sense of the diff. ⚠️ 

I saw this repo on my "For you" page on GitHub, so I decided I should check it out 😁 And why not do a little drive-by at improving the dev/contributor experience along the way?

The changes fall roughly in these categories:

* Dev tooling to automating formatting and linting:
    - Added Black formatter (with notebook support!)
    - Added ruff linter
    - Added pre-commit hooks to the repo
    - Added jupyter to dev dependencies explicitly
* Improved dev documentation:
    - Added `CONTRIBUTING.md` with basic poetry setup
    - Documented the tooling mentioned above
* Improved project metadata:
    - Added fancy badges to the README
    - Added PyPI keywords
    - Added PyPI classifiers
* Linting:
    - Enabled and fixed many rules (separate commits to keep diff obvious):
        + flake8
        + pycodestyle
        + isort
        + pyupgrade
        + bugbear
    - Only kept the most obvious changes, some are more involved and I wanted to be sure not to break anything.
* Reformatting:
    - One big commit then you shouldn't see them again
    - Can configure Git to ignore that commit in `git blame`

### CODE REVIEW

**Comment by charliereese** [comment]
Hey [samueldg](https://github.com/samueldg)!

Thank you for contributing; excited to review this later today :)

Cheers,

Charlie

**Comment by charliereese** [comment]
RE _dev tooling to automating formatting and linting_ additions: 

- They are great; they align the repo's tooling with best practices
- They're best in a separate PR

**Comment by charliereese** [comment]
Re _Improved dev documentation:_

- All of your additions look great!
- They're best in a separate PR

**Comment by charliereese** [comment]
RE _metadata, linting, and reformatting_:

- All of your additions look great!
- They're best in a separate PR (ideally for metadata and for linting / reformatting)

**Comment by charliereese** [comment]
[samueldg](https://github.com/samueldg) are you willing to split the PRs as per above? If so, I'll merge them with gratitude; thank you for helping make InvestOS better!

Otherwise, I'm happy to split the PR up on your behalf :)

**Comment by charliereese** [comment]
> @charliereese Yes I can certainly chop this up in more PRs! I should have some time this evening.

Amazing - appreciate you! 

No specific rush :)

**Comment by samueldg** [comment]
@charliereese I separated the first batch of PRs:

- #2 
- #3 
- #4 
- #5 

This covers all the changes that are relatively self-contained, and that we can push to `main` without any inter-dependencies.

Once they're merged, I'll be able to cherry-pick the reformatting/linting as well as the introduction of new tooling.

**Comment by charliereese** [comment]
Amazing! Will merge these tomorrow :)

**Comment by samueldg** [comment]
@charliereese two new PRs spun off from this one:

* https://github.com/charliereese/investos/pull/7
* https://github.com/charliereese/investos/pull/8

I'll wait for those to be merged before making a PR with the more elaborate linter config + fixes, in order to minimize noisy review and/or merge conflicts.

**Comment by samueldg** [comment]
Closing this, has been superseded by PRs 2-14

**Pull request closed without merging**
